### ISSUE TITLE
Not replacement itemView -> childView

### ISSUE THREAD

**Issue by ryotakato** [marionettejs/Marionette.Upgrade#35]
Hi, This is Nice tool ! Thank you.

I try change Marionette 1.8 -> Marionette 2.2.
But did'nt replace "itemView" to "childVIew" in CollectionView .

Code is 
```js
  return Backbone.Marionette.CollectionView.extend({
    itemView: SampleView,
    tagName:"ul",
    initialize: function() {
    }
  });
```

Why not ?  Colon ?

**Comment by jmeas** [comment]
You said it yourself, the new attribute name is `childView`. Change that, and it should work.

**Comment by thejameskyle** [comment]
uh @jmeas if the upgrade script didnt do that dont you think thats worth looking into?

**Comment by jmeas** [comment]
Ah misread the issue!

**Comment by ryotakato** [comment]
Sorry, do not have enough words.

**Comment by jmeas** [comment]
Nah it's my fault @ryotakato. I shouldn't reply from my iPhone when I'm out buying groceries :P

**Comment by jasonLaster** [comment]
@ryotakato thanks for making the issue. The tool should absolutely catch this. Because it's actually one small Python file with some regexes, id appreciate it if you took a look. The easiest thing to do is comment out the irrelevant ones and see what happens.

**Comment by ryotakato** [comment]
I tryed. 
And to keep apologized earlier.

In Using of README.md 

```bash
$ ./upgrade.py PATH_TO_PROJECT_DIR
```

But I have tryed 

```bash
$ ./Marionette.Upgrade/upgrade.py PATH_TO_PROJECT_DIR
```

so, I didn't notice to following sentence.

```
sh: ./bin/codemod.py: No such file or directory
```


I'm sorry to be fuss.


How about that change upgrade.py ? like this,

```python
codemod = "./bin/codemod.py"
```

to

```python
codemod = "%s/bin/codemod.py" %  path.dirname(__file__)
```

**Comment by jasonLaster** [comment]
Sure. PR it up

**Comment by samccone** [comment]
:+1:

**Comment by ryotakato** [comment]
This is my first pull request.
Thank you, for @jmeas , @thejameskyle , @jasonLaster , @samccone

**Comment by jasonLaster** [comment]
Got it! Welcome to OSS

**Comment by ryotakato** [comment]
Thanks !
